blueprint:
  name: Alexa Music Group - Send Actionable Notification at Time
  description: |
    Choose a person to send a notification to at a certain time. Conditioned by zone.
    
    You must set up the Alexa Media Player custom component, a new input_text entity (I used HA helpers), and actionable notifications in your configuration.yaml for this to work.
    
    My configuration.yaml file has an entry that looks something like this (minus the periods)
    
    ios:
    ..push:
    ....categories:
    ......- name: Todays Music
    ........identifier: 'todaysmusic'
    ........actions:
    ..........- identifier: 'INPUT_MUSIC'
    ............title: "Type what you'd like to hear"
    ............behavior: 'textInput'
    ............textInputButtonTitle: 'Submit'
    ............textInputPlaceholder: 'music'
    ..........- identifier: 'JAZZ_MUSIC'
    ............title: 'Jazz Radio'
    ..........- identifier: 'CLASSICAL_MUSIC'
    ............title: 'Classical Radio'
    ..........- identifier: 'RANDOM_MUSIC'
    ............title: 'Random' 
    
    If you want to add a custom choice for yourself (or change one of these choices), just use this same naming convention.
  domain: automation
  input:
    actionable_notification_identifier:
      name: Name of Your Actionable Notification Identifier
      description: What is the identifier of the actionable notification you created in config.yaml? ex - todaysmusic
      selector:
        text:
      default: todaysmusic
    time_on:
      name: Time to send notification
      description: What time do you want the actionable notification to send?
      selector:
        time:
      default: '16:15:00'
    person_entity:
      name: Person
      description: Who is the notification Zone-conditioned by?
      selector:
        entity:
          domain: person
    zone_entity:
      name: Zone
      description: What zone do you want to use for the condition?
      selector:
        entity:
          domain: zone
    notify_device:
      name: Device to notify
      description: Device needs to run the official Home Assistant app to receive notifications.
      selector:
        device:
          integration: mobile_app
trigger:
  platform: time
  at: !input time_on
  
condition:
  condition: zone
  entity_id: !input person_entity
  zone: !input zone_entity
    
action:
  domain: mobile_app
  type: notify
  device_id: !input notify_device
  data:
    push:
      category: !input actionable_notification_identifier
  message: What do you want to hear today?
  title: Arriving Home Music
