blueprint:
  name: Alexa Music Group - Send Actionable Notification
  description: Arriving Home Music Actionable Notification
  domain: automation
  input:
    person_entity:
      name: Person
      selector:
        entity:
          domain: person
    zone_entity:
      name: Zone
      selector:
        entity:
          domain: zone
    notify_device:
      name: Device to notify
      description: Device needs to run the official Home Assistant app to receive notifications.
      selector:
        device:
          integration: mobile_app
trigger:
  platform: time
  at: '16:15:00'

condition:
  condition: zone
  entity_id: !input person_entity
  zone: ! input zone_entity
    
action:
  service: !input notify_device
  data:
    data:
      push:
        category: todaysmusic
    message: What do you want to hear today?
    title: Arriving Home Music
